# Generated by Django 5.0.14 on 2026-09-23 09:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shiftswaprequest',
            name='assignment',
        ),
        migrations.AddField(
            model_name='shiftswaprequest',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='shiftswaprequest',
            name='mode',
            field=models.CharField(choices=[('self', 'Change My Shift'), ('trade', 'Trade With Colleague')], default='self', max_length=10),
        ),
        migrations.AddField(
            model_name='shiftswaprequest',
            name='requested_shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requested_in_swaps', to='hrm.shift'),
        ),
        migrations.AddField(
            model_name='shiftswaprequest',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='shiftswaprequest',
            name='trade_with',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='swap_requests_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='StaffWeeklyOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_off_days', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['weekday'],
                'unique_together': {('staff', 'weekday')},
            },
        ),
    ]
