# Generated by Django 5.0.14 on 2026-09-23 11:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0002_remove_shiftswaprequest_assignment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staffweeklyoff',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='staffweeklyoff',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='rejection_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='staffweeklyoff',
            name='weekdays',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='staffweeklyoff',
            name='staff',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_off', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='staffweeklyoff',
            name='weekday',
        ),
    ]
