# Generated by Django 5.0.14 on 2026-09-23 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0003_alter_staffweeklyoff_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancerecord',
            name='clock_in_photo',
        ),
        migrations.RemoveField(
            model_name='attendancerecord',
            name='clock_out_photo',
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='clock_in_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='clock_out_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
