# Generated by Django 5.0.14 on 2026-09-12 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_site', '0007_remove_roomtype_total_rooms_alter_roomtype_price_max_and_more'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='linked_menu_item',
            field=models.OneToOneField(blank=True, help_text='If guests can order this, link it to its menu listing so restocking never touches the menu.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_item', to='public_site.menuitem'),
        ),
    ]
