# Generated by Django 5.0.14 on 2026-09-15 12:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_stockitem_linked_menu_item'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WastageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reason', models.CharField(max_length=200)),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('logged_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wastage_logged', to=settings.AUTH_USER_MODEL)),
                ('stock_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wastage_records', to='store.stockitem')),
            ],
        ),
    ]
