# Generated by Django 5.0.14 on 2026-09-17 11:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_dailyusagelog_dailyusageitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyusagelog',
            name='confirmed_at',
        ),
        migrations.RemoveField(
            model_name='dailyusagelog',
            name='confirmed_by',
        ),
        migrations.RemoveField(
            model_name='dailyusagelog',
            name='status',
        ),
        migrations.AddField(
            model_name='dailyusageitem',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyusageitem',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usage_items_confirmed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dailyusageitem',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
    ]
