# Generated by Django 5.0.14 on 2026-09-17 18:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_dailyusagelog_confirmed_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disbursementpurchase',
            name='disbursement',
        ),
        migrations.RemoveField(
            model_name='disbursementpurchase',
            name='recorded_by',
        ),
        migrations.RemoveField(
            model_name='disbursementpurchase',
            name='stock_item',
        ),
        migrations.AlterField(
            model_name='dailyusagelog',
            name='department',
            field=models.CharField(choices=[('kitchen', 'Kitchen / Restaurant'), ('bar', 'Bar'), ('housekeeping', 'Housekeeping / Rooms'), ('front_desk', 'Front Desk / Reception'), ('conference', 'Conference & Events'), ('general', 'General / Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='department',
            field=models.CharField(choices=[('kitchen', 'Kitchen / Restaurant'), ('bar', 'Bar'), ('housekeeping', 'Housekeeping / Rooms'), ('front_desk', 'Front Desk / Reception'), ('conference', 'Conference & Events'), ('general', 'General / Other')], max_length=20),
        ),
        migrations.CreateModel(
            name='PurchaseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('kitchen', 'Kitchen / Restaurant'), ('bar', 'Bar'), ('housekeeping', 'Housekeeping / Rooms'), ('front_desk', 'Front Desk / Reception'), ('conference', 'Conference & Events'), ('general', 'General / Other')], max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_cost', models.DecimalField(decimal_places=2, help_text='Price paid per unit', max_digits=10)),
                ('vat_inclusive', models.BooleanField(default=True, help_text='Is the unit cost above already inclusive of 16% VAT?')),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('purchased_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When the purchase actually happened')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('purchased_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases_made', to=settings.AUTH_USER_MODEL)),
                ('stock_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_logs', to='store.stockitem')),
            ],
            options={
                'ordering': ['-purchased_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='purchase_receipts/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='store.purchaselog')),
            ],
        ),
        migrations.DeleteModel(
            name='Disbursement',
        ),
        migrations.DeleteModel(
            name='DisbursementPurchase',
        ),
    ]
