# Generated by Django 5.0.14 on 2026-09-18 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_stockitem_par_level_stocktake_stocktakeline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasereceipt',
            name='supplier',
        ),
        migrations.AddField(
            model_name='purchaselog',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to='store.supplier'),
        ),
    ]
