# Generated by Django 5.0.14 on 2026-09-19 15:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_remove_purchasereceipt_supplier_purchaselog_supplier'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyusageitem',
            name='custom_unit_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cost per unit for items not in the stock catalog', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='purchasereceipt',
            name='purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='store.purchaselog'),
        ),
        migrations.CreateModel(
            name='PurchaseBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchased_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('purchased_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_batches', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches', to='store.supplier')),
            ],
        ),
        migrations.AddField(
            model_name='purchaselog',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lines', to='store.purchasebatch'),
        ),
        migrations.AddField(
            model_name='purchasereceipt',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='store.purchasebatch'),
        ),
    ]
