# Generated by Django 5.0.14 on 2026-09-19 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_dailyusageitem_custom_unit_cost_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaselog',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='purchasereceipt',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='dailyusageitem',
            name='custom_unit_cost',
        ),
        migrations.AlterField(
            model_name='purchasereceipt',
            name='purchase',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='store.purchaselog'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='PurchaseBatch',
        ),
    ]
