# Generated by Django 5.0.14 on 2026-09-19 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_remove_purchaselog_batch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyusageitem',
            name='custom_unit_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cost per unit for items not in the stock catalog', max_digits=10, null=True),
        ),
    ]
