# Generated by Django 5.0.14 on 2026-09-29 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_dailyusageitem_custom_unit_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockFloatDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('opening', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('taken', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('consumed', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('wasted', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('closing', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('stock_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='float_days', to='store.stockitem')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('stock_item', 'date')},
            },
        ),
    ]
