# Generated by Django 5.0.14 on 2026-09-05 20:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0001_create_role_groups'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_id', models.CharField(help_text='National ID or Passport number. Used to identify this staff member on any record they handle.', max_length=20, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('department_note', models.CharField(blank=True, help_text="Optional, e.g. 'Night shift', 'Gate 2'", max_length=100)),
                ('is_active_staff', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
