# Generated by Django 5.0.14 on 2026-09-05 21:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GateLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(max_length=150)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('vehicle_make', models.CharField(blank=True, max_length=100)),
                ('plate_number', models.CharField(max_length=20)),
                ('purpose', models.CharField(blank=True, help_text='e.g. Visiting guest, Delivery, Meeting', max_length=150)),
                ('parking_spot', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('inside', 'Inside'), ('exited', 'Exited')], default='inside', max_length=10)),
                ('entry_time', models.DateTimeField(auto_now_add=True)),
                ('exit_time', models.DateTimeField(blank=True, null=True)),
                ('logged_in_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gate_entries_logged', to=settings.AUTH_USER_MODEL)),
                ('logged_out_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gate_exits_logged', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-entry_time'],
            },
        ),
    ]
