# Generated by Django 5.0.14 on 2026-09-12 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='settlement_group',
            field=models.UUIDField(blank=True, db_index=True, help_text='Groups payments made together as one settlement, e.g. room + all room service in one go.', null=True),
        ),
    ]
