# Generated by Django 5.0.14 on 2026-09-15 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_payment_settlement_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='amount_tendered',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='What the customer actually handed over. Leave blank if exact.', max_digits=10, null=True),
        ),
    ]
