# Generated by Django 5.0.14 on 2026-09-21 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_add_hr_manager_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='date_joined_role',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='department',
            field=models.CharField(blank=True, choices=[('front_office', 'Front Office'), ('housekeeping', 'Housekeeping'), ('kitchen', 'Kitchen'), ('restaurant', 'Restaurant'), ('bar', 'Bar'), ('security', 'Security'), ('store', 'Store & Inventory'), ('management', 'Management'), ('hr', 'Human Resources'), ('maintenance', 'Maintenance')], max_length=20),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='employment_status',
            field=models.CharField(choices=[('active', 'Active'), ('on_leave', 'On Leave'), ('suspended', 'Suspended'), ('terminated', 'Terminated')], default='active', max_length=15),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='pay_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='pay_type',
            field=models.CharField(choices=[('monthly', 'Monthly Salary'), ('daily', 'Daily Rate'), ('hourly', 'Hourly Rate')], default='monthly', max_length=10),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='position',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
