# Generated by Django 5.0.14 on 2026-09-24 16:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_staffprofile_date_joined_role_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmploymentAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('hired', 'Hired'), ('promoted', 'Promoted'), ('demoted', 'Demoted'), ('suspended', 'Suspended'), ('reinstated', 'Reinstated'), ('terminated', 'Terminated'), ('updated', 'Details Updated')], max_length=15)),
                ('previous_position', models.CharField(blank=True, max_length=100)),
                ('new_position', models.CharField(blank=True, max_length=100)),
                ('previous_department', models.CharField(blank=True, max_length=20)),
                ('new_department', models.CharField(blank=True, max_length=20)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employment_actions_performed', to=settings.AUTH_USER_MODEL)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employment_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
