# Generated by Django 5.0.14 on 2026-10-04 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_employmentaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='recorded_from',
            field=models.CharField(blank=True, choices=[('reception', 'Reception'), ('rooms', 'Rooms'), ('restaurant', 'Restaurant'), ('bar', 'Bar')], db_index=True, editable=False, help_text='Which desk captured this payment. Set automatically by the view, not by the user.', max_length=15),
        ),
    ]
