# Generated by Django 5.0.14 on 2026-09-02 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_site', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='tier',
            field=models.CharField(choices=[('regular', 'Regular'), ('vip', 'VIP')], default='regular', max_length=10),
        ),
    ]
