# Generated by Django 5.0.14 on 2026-09-02 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_site', '0002_menuitem_tier'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConferenceRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tier', models.CharField(choices=[('regular', 'Regular'), ('vip', 'VIP')], max_length=10)),
                ('description', models.TextField(blank=True)),
                ('price_min', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('price_max', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('capacity', models.PositiveIntegerField(default=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RenameField(
            model_name='menuitem',
            old_name='price',
            new_name='regular_price',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='guest_email',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='image',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='tier',
        ),
        migrations.RemoveField(
            model_name='roomtype',
            name='image',
        ),
        migrations.RemoveField(
            model_name='roomtype',
            name='price',
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_type',
            field=models.CharField(choices=[('room', 'Room'), ('conference', 'Conference')], default='room', max_length=12),
        ),
        migrations.AddField(
            model_name='booking',
            name='guest_id_no',
            field=models.CharField(default='', help_text='National ID or Passport number', max_length=20),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='vip_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Leave blank if this item has no separate VIP price', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='tier',
            field=models.CharField(choices=[('regular', 'Regular'), ('vip', 'VIP')], default='regular', max_length=10),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='price_max',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='price_min',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='room_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='public_site.roomtype'),
        ),
        migrations.AddField(
            model_name='booking',
            name='conference_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='public_site.conferenceroom'),
        ),
        migrations.CreateModel(
            name='MenuItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='menu_items/')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='public_site.menuitem')),
            ],
        ),
        migrations.CreateModel(
            name='RoomTypeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='room_types/')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='public_site.roomtype')),
            ],
        ),
    ]
