# Generated by Django 5.0.14 on 2026-09-03 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public_site', '0004_conversation_emailverification_chatmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactMessage',
        ),
    ]
