# Generated by Django 5.0.14 on 2026-09-12 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_site', '0006_room_booking_assigned_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomtype',
            name='total_rooms',
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='price_max',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='price_min',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
