# Generated by Django 5.0.14 on 2026-09-12 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_site', '0007_remove_roomtype_total_rooms_alter_roomtype_price_max_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='room_booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_service_orders', to='public_site.booking'),
        ),
    ]
