# Generated by Django 5.0.14 on 2026-09-14 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_site', '0008_order_room_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, unique=True)),
                ('capacity', models.PositiveIntegerField(default=4)),
                ('status', models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('needs_cleaning', 'Needs Cleaning')], default='available', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='menuitem',
            name='course',
            field=models.CharField(choices=[('starter', 'Starter'), ('main', 'Main Course'), ('dessert', 'Dessert')], default='main', max_length=10),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='is_quick_serve',
            field=models.BooleanField(default=False, help_text="Already made / doesn't need active cooking (e.g. bottled drinks, pre-made snacks). Skips the 'Preparing' step in the kitchen queue."),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='prep_status',
            field=models.CharField(choices=[('queued', 'Queued'), ('preparing', 'Preparing'), ('ready', 'Ready to Serve'), ('served', 'Served')], default='queued', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='public_site.table'),
        ),
    ]
