# Generated by Django 5.0.14 on 2026-09-14 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_site', '0009_table_menuitem_course_menuitem_is_quick_serve_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='serving_point',
            field=models.CharField(choices=[('kitchen', 'Kitchen (Restaurant)'), ('bar', 'Bar')], default='kitchen', help_text='For drinks: where this is served from. Tea/coffee/water/soft drinks = Kitchen. Beer/spirits/wine/cocktails = Bar.', max_length=10),
        ),
        migrations.AddField(
            model_name='table',
            name='is_vip',
            field=models.BooleanField(default=False, help_text='VIP dining area. New orders here default to VIP pricing.'),
        ),
    ]
