# Generated by Django 5.0.14 on 2026-09-14 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_site', '0010_menuitem_serving_point_table_is_vip'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('dine_in', 'Dine In'), ('takeaway', 'Takeaway'), ('conference', 'Conference Catering'), ('event', 'Event / Bulk Order')], default='dine_in', max_length=12),
        ),
        migrations.AddField(
            model_name='order',
            name='party_size',
            field=models.PositiveIntegerField(blank=True, help_text='Number of guests, for event/bulk orders', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='served_at',
            field=models.CharField(blank=True, help_text='For conference/event orders: location or event name', max_length=150),
        ),
    ]
