# Generated by Django 5.0.14 on 2026-09-14 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_site', '0011_order_order_type_order_party_size_order_served_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
