# Generated by Django 5.0.14 on 2026-09-15 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_site', '0014_bartab_happyhourwindow_orderitem_unit_price_override_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='cost_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='What one unit costs you to buy. Used for profit tracking.', max_digits=10, null=True),
        ),
    ]
