# Generated by Django 5.0.14 on 2026-09-17 11:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_site', '0016_lostfounditem_maintenancerequest_roomcleaninglog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomTransferLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=200)),
                ('transferred_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='public_site.booking')),
                ('from_room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_from', to='public_site.room')),
                ('to_room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_to', to='public_site.room')),
                ('transferred_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='room_transfers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
