# Generated by Django 5.0.14 on 2026-09-26 22:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_site', '0017_roomtransferlog'),
        ('store', '0012_dailyusageitem_custom_unit_cost'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='recipe_cost_snapshot',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Ingredient cost for this line, captured the moment stock was deducted. Frozen even if ingredient prices or the recipe change later.', max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yield_quantity', models.PositiveIntegerField(default=1, help_text="How many servings/plates this batch produces, e.g. 20 for '20 chapatis'")),
                ('notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipes_created', to=settings.AUTH_USER_MODEL)),
                ('menu_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recipe', to='public_site.menuitem')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('unit', models.CharField(choices=[('kg', 'Kilogram'), ('g', 'Gram'), ('l', 'Litre'), ('ml', 'Millilitre'), ('piece', 'Piece'), ('pack', 'Pack'), ('box', 'Box'), ('bottle', 'Bottle')], max_length=10)),
                ('note', models.CharField(blank=True, help_text="e.g. 'diced' — not used in costing", max_length=100)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='public_site.recipe')),
                ('stock_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipe_uses', to='store.stockitem')),
            ],
        ),
    ]
