# Generated by Django 5.0.14 on 2026-09-27 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_site', '0018_orderitem_recipe_cost_snapshot_recipe_and_more'),
        ('store', '0012_dailyusageitem_custom_unit_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeingredient',
            name='custom_name',
            field=models.CharField(blank=True, help_text='For ingredients not yet in the stock catalog (e.g. eggs) — leave stock item blank instead.', max_length=150),
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='custom_unit',
            field=models.CharField(blank=True, choices=[('kg', 'Kilogram'), ('g', 'Gram'), ('l', 'Litre'), ('ml', 'Millilitre'), ('piece', 'Piece'), ('pack', 'Pack'), ('box', 'Box'), ('bottle', 'Bottle')], max_length=10),
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='custom_unit_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Estimated cost per unit, since this isn't tracked in stock yet", max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='stock_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recipe_uses', to='store.stockitem'),
        ),
    ]
