# Generated by Django 5.0.14 on 2026-09-28 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public_site', '0020_order_kitchen_viewed_at_order_kitchen_viewed_by'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WaitlistEntry',
        ),
    ]
