# Generated by Django 5.0.14 on 2026-10-03 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_site', '0021_delete_waitlistentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='staff_unread',
            field=models.BooleanField(default=False),
        ),
    ]
