# Generated by Django 5.0.14 on 2026-10-04 13:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_site', '0022_conversation_staff_unread'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_confirmed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='confirmed_from',
            field=models.CharField(blank=True, choices=[('reception', 'Reception'), ('rooms', 'Rooms'), ('restaurant', 'Restaurant'), ('bar', 'Bar')], editable=False, max_length=15),
        ),
    ]
